services:
  servidor-tcp:
    build: .
    command: java servidor.tcp.PruebaServidorTCP
    ports:
      - "5000:5000" 
    networks:
      - red-proyecto

  servidor-udp:
    build: .
    command: java servidor.udp.PruebaServidorUDP
    ports:
      - "6000:6000/udp"
    networks:
      - red-proyecto

  cliente-interfaz:
    build: .
    # Aquí le decimos a Docker que ejecute tu clase InterfazChat
    command: java vista.InterfazChat
    environment:
      # Esta línea es crucial: le dice al contenedor que envíe los gráficos a tu computadora
      - DISPLAY=host.docker.internal:0.0
    networks:
      - red-proyecto
    depends_on:
      - servidor-tcp
      - servidor-udp

networks:
  red-proyecto:
    driver: bridge